apiVersion: v2
name: cn-asset-manager
description: Cloud asset discovery and cost management tool (AWS)
type: application
version: 0.2.0
appVersion: "0.1.0"

dependencies:
  - name: postgresql
    version: "~18"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
  - name: mysql
    version: "~12"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: mysql.enabled
  - name: redis
    version: "~25"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled
