{{- if eq .Values.database.type "sqlite" -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cn-asset-manager.fullname" . }}-sqlite
  labels:
    {{- include "cn-asset-manager.labels" . | nindent 4 }}
spec:
  {{- if .Values.database.sqlite.storageClass }}
  storageClassName: {{ .Values.database.sqlite.storageClass | quote }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.sqlite.size | default "1Gi" }}
{{- end }}
